version: 0.2

phases:
  install:
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli

      # Install Ruby dependencies from the Gemfile.
      - bundle install

  build:
    commands:
      # Run the tests using RSpec.
      - rspec

artifacts:
  type: zip
  files:
    - '.ebextensions'
    - 'Gemfile'
    - 'README.md'
    - 'config.ru'
    - 'server.rb'
